sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "4"

matrix:
  include:
    - node_js: "lts/*"
      env: LINT=true
script:
  - 'if [ -n "${LINT-}" ]; then yarn lint ; fi'
  - 'if [ -z "${LINT-}" ]; then yarn test-ci ; fi'
after_success:
  - yarn coverage
