sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
env:
  - export WEBPACK_VERSION="2.1.0-beta.22"
  - export WEBPACK_VERSION="1"
before_install:
  - nvm --version
  - node --version
  - npm --version
before_script:
  - 'if [ "$WEBPACK_VERSION" ]; then npm install webpack@$WEBPACK_VERSION; fi'
script:
  - npm run travis
after_success:
  - bash <(curl -s https://codecov.io/bash)
