sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
matrix:
  include:
    - node_js: "6"
      env: WEBPACK_VERSION="1"
    - node_js: "0.10"
      env: WEBPACK_VERSION="1"
before_script:
  - 'if [ "$WEBPACK_VERSION" ]; then npm install webpack@$WEBPACK_VERSION; fi'
script:
  - npm run travis
after_success:
  - bash <(curl -s https://codecov.io/bash)
